In [4]:
# 라이브러리
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

from streamlit_option_menu import option_menu
from datetime import datetime, timedelta, date
from selenium import webdriver
from utils import *
from io import BytesIO
from pyxlsb import open_workbook as open_xlsb

import streamlit as st
import pandas as pd
import numpy as np
import OpenDartReader
import warnings
import time
import re
import os
import copy

warnings.filterwarnings('ignore')

# 파일 불러오기
def read_data(file):
    try:
        output = pd.read_excel(file)
    except:
        def read_xlsx(name):
            instance = xw.App(visible=False)
            xlsx_data = xw.Book(name).sheets[0]
            df = xlsx_data.range('A1').options(pd.DataFrame, index = False, expand = 'table').value
            instance.quit()
            instance.kill()
            return df
        output = read_xlsx(file)
    return output

# 셀레늄 실행
def get_driver():
    options = Options()
    options.add_argument('--disable-gpu')
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--disable-features=NetworkService")
    options.add_argument("--window-size=1920x1080")
    return webdriver.Chrome(options=options)

# RPA 코드 실행
def main():
    ### STEP1. 수집 시작 및 종료 날짜 할당
    # 신고서 제출일, 상장일, 수요예측일 간 차이를 반영하기 위해서 start_dt,start_dt2, start_dt3를 할당
    today = date.today()
    end_dt = datetime.strftime(today, '%Y-%m-%d')
    diff_day = timedelta(days=60)
    start_dt = datetime.strftime(today - diff_day, '%Y-%m-%d')

    ### STEP2. opendartreader 활용, 주어진 기간 내 증권신고서, 증권발행실적 보고서 가져오기
    api_key = '1b39652cef07f626c9d37375edf582ee51b1407f'
    dart = OpenDartReader(api_key)
    opt = '기업금융1부'

    market_dict = {"Y": "코스피","K": "코스닥", "N": "코넥스", "E": "기타"}

    info_df = dart.list(start=start_dt, end=end_dt, kind_detail='C001')
    info_df = pd.concat([info_df, dart.list(start=start_dt, end=end_dt, kind_detail='G002')])
    info_df = info_df.loc[[True if "증권발행실적보고서" in x else False for x in info_df.report_nm]]
    info_df = info_df.loc[info_df.corp_cls.isin(['Y', 'K'])]
    info_df.corp_cls = info_df.corp_cls.map(market_dict)
    
    ### STEP3. KIND 수집 항목 가져오기, 셀레늄 사용, 이 경우 viz_opt를 True로 함으로써 수집해야 함, False 시 조회 불가
    driver = get_driver()
    driver.set_window_size(1920, 1080)
    first_df = kind_main(driver, info_df, start_dt, end_dt)

    ### STEP4. ipo stock 수집 항목 가져오기, 셀레늄 사용
    driver = get_driver()
    driver.set_window_size(1920, 1080)
    ipo_df = ipo_main(driver, info_df)
    first_df = pd.merge(first_df, ipo_df, on = 'corp_name', how = 'left')

    ### STEP5. 38커뮤니케이션 수집 항목 가져오기
    outer_df = get_38(start_dt, end_dt)
    second_df = pd.merge(first_df, outer_df, on = 'stock_code', how = 'inner')

    ### STEP6. 현업 양식에 맞게끔 변경, opendartreader 활용, 인수인 정보 수집
    third_df = get_dd(dart, second_df)
    third_df, fourth_df = get_d_tables(dart, third_df)

    form_1 = change_form(fourth_df, opt, 1)
    form_2 = change_form(third_df, opt, 2)
    form_3 = change_form(fourth_df, opt, 3)

    form_1 = form_1.loc[form_1['상장일'] >= start_dt]
    form_2 = form_2.loc[form_2['상장일'] >= start_dt]
    form_3 = form_3.loc[form_3['상장일'] >= start_dt]
    
    ### STEP7. 파일 저장 및 갱신
    data_path = './datasets/'

    if not os.path.isdir(data_path):
        os.mkdir(data_path)

    if os.path.isfile(data_path + "corporate-finance-data.xlsx"):
        o_form1 = read_data(data_path + "form1.xlsx")
        o_form2 = read_data(data_path + "form2.xlsx")
        o_form3 = read_data(data_path + "form3.xlsx")

        o_form1 = pd.concat([o_form1, form_1]).sort_values("상장일").drop_duplicates()
        o_form2 = pd.concat([o_form2, form_2]).sort_values("청약일").drop_duplicates()
        o_form3 = pd.concat([o_form3, form_3]).sort_values("인수기관").drop_duplicates()

        o_form1.to_excel(data_path + "form1.xlsx", index = False)
        o_form2.to_excel(data_path + "form2.xlsx", index = False)
        o_form3.to_excel(data_path + "form3.xlsx", index = False)

        with pd.ExcelWriter(data_path + "corporate-finance-data.xlsx", engine = 'xlsxwriter') as writer:
            o_form1.to_excel(writer, sheet_name="01_리그테이블", index=False)
            o_form2.to_excel(writer, sheet_name="02_통합집계_Rawdata", index=False)
            o_form3.to_excel(writer, sheet_name="03_IPO현황_Summary", index=False)
    else:
        form_1.to_excel(data_path + "form1.xlsx", index = False)
        form_2.to_excel(data_path + "form2.xlsx", index = False)
        form_3.to_excel(data_path + "form3.xlsx", index = False)

        with pd.ExcelWriter(data_path + "corporate-finance-data.xlsx", engine = 'xlsxwriter') as writer:
            form_1.to_excel(writer, sheet_name="01_리그테이블", index=False)
            form_2.to_excel(writer, sheet_name="02_통합집계_Rawdata", index=False)
            form_3.to_excel(writer, sheet_name="03_IPO현황_Summary", index=False)

if __name__=="__main__":
    main()

In [6]:
data_path = './datasets/'

In [10]:
a1 = pd.read_excel(data_path + "corporate-finance-data.xlsx", sheet_name = '01_리그테이블')
a2 = pd.read_excel(data_path + "corporate-finance-data.xlsx", sheet_name = '02_통합집계_Rawdata')
a3 = pd.read_excel(data_path + "corporate-finance-data.xlsx", sheet_name = '03_IPO현황_Summary')

In [14]:
today = date.today()
end_dt = datetime.strftime(today, '%Y-%m-%d')
diff_day = timedelta(days=60)
start_dt = datetime.strftime(today - diff_day, '%Y-%m-%d')

In [17]:
a1.loc[(a1['상장일'] >= start_dt) & (a1['상장일'] <= end_dt)]

,상장일,업체,시장구분,발행금액,인수회사,인수금액,인수수수료,청약수수료추정,수수료합계,건수,주관형태,상장트랙,공모가,비율,청약일,납입일,총기관배정수량
40,2023-05-24,기가비스,코스닥,953.85094,삼성,953.85094,-,-,-,-,대표,-,43000,100.0,2023-05-15,2023-05-18,1531524
41,2023-06-01,진영,코스닥,212.50000,하이,212.50000,-,-,-,-,대표,-,5000,100.0,2023-05-22,2023-05-25,3187500
42,2023-06-02,나라셀라,코스닥,290.00000,유진,14.50000,-,-,-,-,인수,-,20000,5.0,2023-05-22,2023-05-25,2088000
43,2023-06-02,나라셀라,코스닥,290.00000,신영,275.50000,-,-,-,-,대표,-,20000,95.0,2023-05-22,2023-05-25,2088000
44,2023-06-08,마녀공장,코스닥,320.00000,한국,288.00000,-,-,-,-,대표,-,16000,90.0,2023-05-25,2023-05-31,3000000
45,2023-06-08,마녀공장,코스닥,320.00000,유진,32.00000,-,-,-,-,인수,-,16000,10.0,2023-05-25,2023-05-31,3000000
46,2023-06-15,큐라티스,코스닥,140.00000,대신,91.00000,-,-,-,-,공동대표,-,4000,65.0,2023-06-05,2023-06-09,5250000
47,2023-06-15,큐라티스,코스닥,140.00000,신영,49.00000,-,-,-,-,공동대표,-,4000,35.0,2023-06-05,2023-06-09,5250000
48,2023-06-16,프로테옴텍,코스닥,72.00000,키움,72.00000,-,-,-,-,대표,-,4500,100.0,2023-06-07,2023-06-12,1152600
49,2023-06-22,하이제8호스팩,코스닥,85.00000,하이,85.00000,-,-,-,-,대표,-,2000,100.0,2023-06-13,2023-06-16,3187500
50,2023-06-23,KB제25호스팩,코스닥,80.00000,KB,80.00000,-,-,-,-,대표,-,2000,100.0,2023-06-13,2023-06-16,3000000
51,2023-06-23,엔에이치스팩29호,코스닥,255.00000,NH,255.00000,-,-,-,-,대표,-,2000,100.0,2023-06-13,2023-06-16,9562500
52,2023-06-28,하나29호스팩,코스닥,90.00000,하나,90.00000,-,-,-,-,대표,-,2000,100.0,2023-06-19,2023-06-22,3375000
53,2023-06-29,시큐센,코스닥,58.44000,신한,58.44000,-,-,-,-,대표,-,3000,100.0,2023-06-20,2023-06-23,1461000
54,2023-06-30,알멕,코스닥,500.00000,NH,500.00000,-,-,-,-,대표,-,50000,100.0,2023-06-20,2023-06-23,637545
55,2023-06-30,오픈놀,코스닥,165.00000,하나,165.00000,-,-,-,-,대표,-,10000,100.0,2023-06-21,2023-06-26,1237500
56,2023-07-06,이노시뮬레이션,코스닥,135.00000,하나,135.00000,-,-,-,-,대표,-,15000,100.0,2023-06-27,2023-06-30,660177
57,2023-07-06,교보14호스팩,코스닥,77.00000,교보,77.00000,-,-,-,-,대표,-,2000,100.0,2023-06-26,2023-06-29,2887500
58,2023-07-12,DB금융스팩11호,코스닥,100.00000,DB,100.00000,-,-,-,-,대표,-,2000,100.0,2023-07-03,2023-07-06,3750000
59,2023-07-14,필에너지,코스닥,956.25000,미래,812.81250,-,-,-,-,대표,-,34000,85.0,2023-07-05,2023-07-10,3825000
60,2023-07-14,필에너지,코스닥,956.25000,삼성,143.43750,-,-,-,-,인수단,-,34000,15.0,2023-07-05,2023-07-10,3825000
61,2023-07-19,센서뷰,코스닥,175.50000,삼성,175.50000,-,-,-,-,대표,-,4500,100.0,2023-07-10,2023-07-13,2925000
62,2023-07-20,와이랩,코스닥,270.00000,한국,270.00000,-,-,-,-,대표,-,9000,100.0,2023-07-10,2023-07-13,2160000

In [18]:
a2

,청약일,회사명,대표주관회사,납입일,상장일,공모금액(천원),공모주수,기준가(평가가치),1차발행가액(하단),1차발행가액(상단),수요예측가중평균가,확정발행가액,결정비율,공모비율,구주매출비중,상장요건,코넥스여부,경쟁률,인수수수료(천원),수수료율
0,2023-01-10,티이엠씨,한화,2023-01-13,2023-01-19,50400000.0,1800000,-,32000,38000,-,28000,-,-,0.000000,-,-,0.81 : 1,-,-
1,2023-01-10,한주라이트메탈,"미래, 현대차",2023-01-13,2023-01-19,20150000.0,6500000,-,2700,3100,-,3100,-,-,35.384615,-,-,565.18 : 1,-,-
2,2023-01-16,오브젠,한국,2023-01-19,2023-01-30,13967208.0,775956,-,18000,24000,-,18000,-,-,0.000000,-,-,5.97 : 1,-,-
3,2023-01-16,미래반도체,신한,2023-01-19,2023-01-27,21600000.0,3600000,-,5300,6000,-,6000,-,-,0.000000,-,-,938.27 : 1,-,-
4,2023-01-25,삼기이브이,대신,2023-01-30,2023-02-03,39072407.0,3552037,-,13800,16500,-,11000,-,-,40.000006,-,-,117.63 : 1,-,-
5,2023-01-26,스튜디오미르,미래,2023-01-31,2023-02-07,19500000.0,1000000,-,15300,19500,-,19500,-,-,20.000000,-,-,1592 : 1,-,-
6,2023-01-31,꿈비,유진,2023-02-03,2023-02-09,10000000.0,2000000,-,4000,4500,-,5000,-,-,12.500000,-,-,1772.59 : 1,-,-
7,2023-02-06,샌즈랩,키움,2023-02-09,2023-02-15,38850000.0,3700000,-,8500,10500,-,10500,-,-,18.918919,-,-,868.07 : 1,-,-
8,2023-02-07,제이오,한국,2023-02-10,2023-02-16,52000000.0,4000000,-,10000,13000,-,13000,-,-,0.000000,-,-,142.47 : 1,-,-
9,2023-02-09,이노진,IBK,2023-02-14,2023-02-20,7800000.0,2600000,-,2500,3000,-,3000,-,-,0.000000,-,-,1643.88 : 1,-,-
10,2023-02-14,미래에셋비전스팩2호,미래,2023-02-17,2023-02-24,9300000.0,4650000,-,2000,2000,-,2000,-,-,0.000000,-,-,253.85 : 1,-,-
11,2023-02-16,유안타제13호스팩,유안타,2023-02-21,2023-02-28,17000000.0,8500000,-,2000,2000,-,2000,-,-,0.000000,-,-,16.36447 : 1,-,-
12,2023-02-27,엔에이치스팩28호,NH,2023-03-03,2023-03-09,6800000.0,3400000,-,2000,2000,-,2000,-,-,0.000000,-,-,374.56 : 1,-,-
13,2023-03-02,금양그린파워,삼성,2023-03-07,2023-03-13,30073200.0,3007320,-,6700,8000,-,10000,-,-,0.000000,-,-,1312.1 : 1,-,-
14,2023-03-06,미래에셋드림스팩1호,미래,2023-03-09,2023-03-15,70000000.0,7000000,-,10000,10000,-,10000,-,-,0.000000,-,-,0.46 : 1,-,-
15,2023-03-07,유안타제12호스팩,유안타,2023-03-10,2023-03-17,9000000.0,4500000,-,2000,2000,-,2000,-,-,0.000000,-,-,1.54 : 1,-,-
16,2023-03-13,한화리츠,"한국, 한화",2023-03-16,2023-03-27,116000000.0,23200000,-,5000,5000,-,5000,-,-,0.000000,-,-,0.51 : 1,-,-
17,2023-03-20,LB인베스트먼트,미래,2023-03-23,2023-03-29,23552039.7,4618047,-,4400,5100,-,5100,-,-,33.333333,-,-,1165.76 : 1,-,-
18,2023-03-21,지아이이노베이션,"NH, 하나",2023-03-24,2023-03-30,26000000.0,2000000,-,16000,21000,-,13000,-,-,0.000000,-,-,262 : 1,-,-
19,2023-03-27,IBKS제22호스팩,IBK,2023-03-30,2023-04-06,8000000.0,4000000,-,2000,2000,-,2000,-,-,0.000000,-,-,51.76 : 1,-,-
20,2023-03-27,삼성FN리츠,"삼성, 한국",2023-03-30,2023-04-10,118900000.0,23780000,-,5000,5000,-,5000,-,-,0.000000,-,-,1.86 : 1,-,-
21,2023-03-27,하나27호스팩,하나,2023-03-30,2023-04-06,10000000.0,5000000,-,2000,2000,-,2000,-,-,0.000000,-,-,2.45 : 1,-,-
22,2023-03-28,미래에셋비전스팩3호,미래,2023-03-31,2023-04-07,9000000.0,4500000,-,2000,2000,-,2000,-,-,0.000000,-,-,35.13 : 1,-,-
23,2023-04-17,마이크로투나노,한국,2023-04-20,2023-04-26,15500000.0,1000000,-,13500,15500,-,15500,-,-,0.000000,-,-,1636.6 : 1,-,-
24,2023-04-18,토마토시스템,교보,2023-04-21,2023-04-27,15652000.0,860000,-,18200,22200,-,18200,-,-,0.000000,-,-,266.16 : 1,-,-
25,2023-05-08,키움제8호스팩,키움,2023-05-11,2023-05-17,10000000.0,5000000,-,2000,2000,-,2000,-,-,0.000000,-,-,11.23 : 1,-,-
26,2023-05-08,트루엔,미래,2023-05-11,2023-05-17,30000000.0,2500000,-,10000,12000,-,12000,-,-,0.000000,-,-,1481.84 : 1,-,-
27,2023-05-09,씨유박스,신한,2023-05-12,2023-05-19,22500000.0,1500000,-,17200,23200,-,15000,-,-,0.000000,-,-,56.88 : 1,-,-
28,2023-05-10,모니터랩,미래,2023-05-15,2023-05-19,19600000.0,2000000,-,7500,9800,-,9800,-,-,0.000000,-,-,1785.1177 : 1,-,-
29,2023-05-15,기가비스,삼성,2023-05-18,2023-05-24,95385094.0,2218258,-,34400,39700,-,43000,-,-,6.649362,-,-,823.74 : 1,-,-
30,2023-05-22,나라셀라,신영,2023-05-25,2023-06-02,29000000.0,1450000,-,20000,24000,-,20000,-,-,15.000000,-,-,4.84 : 1,-,-
31,2023-05-22,진영,하이,2023-05-25,2023-06-01,21250000.0,4250000,-,3600,4200,-,5000,-,-,0.000000,-,-,1452.49 : 1,-,-
32,2023-05-25,마녀공장,한국,2023-05-31,2023-06-08,32000000.0,2000000,-,12000,14000,-,16000,-,-,0.000000,-,-,1265.33 : 1,-,-
33,2023-06-05,큐라티스,"대신, 신영",2023-06-09,2023-06-15,14000000.0,3500000,-,6500,8000,-,4000,-,-,0.000000,-,-,155.8 : 1,-,-
34,2023-06-07,프로테옴텍,키움,2023-06-12,2023-06-16,7200000.0,1600000,-,5400,6600,-,4500,-,-,0.000000,-,-,35.43 : 1,-,-
35,2023-06-13,하이제8호스팩,하이,2023-06-16,2023-06-22,8500000.0,4250000,-,2000,2000,-,2000,-,-,0.000000,-,-,125.4 : 1,-,-
36,2023-06-13,KB제25호스팩,KB,2023-06-16,2023-06-23,8000000.0,4000000,-,2000,2000,-,2000,-,-,0.000000,-,-,117.06 : 1,-,-
37,2023-06-13,엔에이치스팩29호,NH,2023-06-16,2023-06-23,25500000.0,12750000,-,2000,2000,-,2000,-,-,0.000000,-,-,18.31 : 1,-,-
38,2023-06-19,하나29호스팩,하나,2023-06-22,2023-06-28,9000000.0,4500000,-,2000,2000,-,2000,-,-,0.000000,-,-,69.3655 : 1,-,-
39,2023-06-20,알멕,NH,2023-06-23,2023-06-30,50000000.0,1000000,-,40000,45000,-,50000,-,-,0.000000,-,-,1355.6 : 1,-,-
40,2023-06-20,시큐센,신한,2023-06-23,2023-06-29,5844000.0,1948000,-,2000,2400,-,3000,-,-,0.000000,-,-,1931.65 : 1,-,-
41,2023-06-21,오픈놀,하나,2023-06-26,2023-06-30,16500000.0,1650000,-,11000,13500,-,10000,-,-,25.210303,-,-,49.04 : 1,-,-
42,2023-06-21,오픈놀,하나,2023-06-26,2023-06-30,16500000.0,1650000,-,11000,13500,-,10000,-,-,25.210303,-,-,49.04 : 1,-,-
43,2023-06-26,교보14호스팩,교보,2023-06-29,2023-07-06,7700000.0,3850000,-,2000,2000,-,2000,-,-,0.000000,-,-,75 : 1,-,-
44,2023-06-27,이노시뮬레이션,하나,2023-06-30,2023-07-06,13500000.0,900000,-,13000,15000,-,15000,-,-,0.000000,-,-,2113.78 : 1,-,-
45,2023-07-03,DB금융스팩11호,DB,2023-07-06,2023-07-12,10000000.0,5000000,-,2000,2000,-,2000,-,-,0.000000,-,-,614.07 : 1,-,-
46,2023-07-05,필에너지,미래,2023-07-10,2023-07-14,95625000.0,2812500,-,26300,30000,-,34000,-,-,33.333333,-,-,1318.3 : 1,-,-
47,2023-07-10,센서뷰,삼성,2023-07-13,2023-07-19,17550000.0,3900000,-,2900,3600,-,4500,-,-,0.000000,-,-,1568 : 1,-,-
48,2023-07-10,와이랩,한국,2023-07-13,2023-07-20,27000000.0,3000000,-,7000,8000,-,9000,-,-,0.000000,-,-,1917.16 : 1,-,-

In [15]:
a3.loc[(a3['상장일'] >= start_dt) & (a3['상장일'] <= end_dt)]

,인수기관,청약일,회사명,대표주관회사,인수회사,납입일,상장일,공모금액(백만원),공모주수,공모가,인수수수료,인수비율
0,DB,2023-07-03,DB금융스팩11호,DB,DB,2023-07-06,2023-07-12,10000.000,5000000,2000,0,100.0
3,KB,2023-06-13,KB제25호스팩,KB,KB,2023-06-16,2023-06-23,8000.000,4000000,2000,0,100.0
8,NH,2023-06-13,엔에이치스팩29호,NH,NH,2023-06-16,2023-06-23,25500.000,12750000,2000,0,100.0
9,NH,2023-06-20,알멕,NH,NH,2023-06-23,2023-06-30,50000.000,1000000,50000,0,100.0
12,교보,2023-06-26,교보14호스팩,교보,교보,2023-06-29,2023-07-06,7700.000,3850000,2000,0,100.0
15,대신,2023-06-05,큐라티스,"대신, 신영","대신, 신영",2023-06-09,2023-06-15,9100.000,3500000,4000,0,65.0
16,미래,2023-07-05,필에너지,미래,"미래, 삼성",2023-07-10,2023-07-14,81281.250,2812500,34000,0,85.0
25,삼성,2023-07-10,센서뷰,삼성,삼성,2023-07-13,2023-07-19,17550.000,3900000,4500,0,100.0
26,삼성,2023-07-05,필에너지,미래,"미래, 삼성",2023-07-10,2023-07-14,14343.750,2812500,34000,0,15.0
27,삼성,2023-05-15,기가비스,삼성,삼성,2023-05-18,2023-05-24,95385.094,2218258,43000,0,100.0
32,신영,2023-05-22,나라셀라,신영,"신영, 유진",2023-05-25,2023-06-02,27550.000,1450000,20000,0,95.0
33,신영,2023-06-05,큐라티스,"대신, 신영","대신, 신영",2023-06-09,2023-06-15,4900.000,3500000,4000,0,35.0
36,신한,2023-06-20,시큐센,신한,신한,2023-06-23,2023-06-29,5844.000,1948000,3000,0,100.0
39,유진,2023-05-25,마녀공장,한국,"한국, 유진",2023-05-31,2023-06-08,3200.000,2000000,16000,0,10.0
40,유진,2023-05-22,나라셀라,신영,"신영, 유진",2023-05-25,2023-06-02,1450.000,1450000,20000,0,5.0
42,키움,2023-06-07,프로테옴텍,키움,키움,2023-06-12,2023-06-16,7200.000,1600000,4500,0,100.0
46,하나,2023-06-27,이노시뮬레이션,하나,하나,2023-06-30,2023-07-06,13500.000,900000,15000,0,100.0
47,하나,2023-06-19,하나29호스팩,하나,하나,2023-06-22,2023-06-28,9000.000,4500000,2000,0,100.0
48,하나,2023-06-21,오픈놀,하나,하나,2023-06-26,2023-06-30,16500.000,1650000,10000,0,100.0
51,하이,2023-06-13,하이제8호스팩,하이,하이,2023-06-16,2023-06-22,8500.000,4250000,2000,0,100.0
52,하이,2023-05-22,진영,하이,하이,2023-05-25,2023-06-01,21250.000,4250000,5000,0,100.0
53,한국,2023-05-25,마녀공장,한국,"한국, 유진",2023-05-31,2023-06-08,28800.000,2000000,16000,0,90.0
55,한국,2023-07-10,와이랩,한국,한국,2023-07-13,2023-07-20,27000.000,3000000,9000,0,100.0