## Import

In [1]:
# 라이브러리
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import ElementNotInteractableException
from selenium import webdriver
from tqdm import tqdm
from bs4 import BeautifulSoup
from IB_utils import *
from utils import kind_main
from datetime import datetime, timedelta, date

import requests
import streamlit as st
import pandas as pd
import numpy as np
import OpenDartReader
import warnings
import time
import re, os

warnings.filterwarnings('ignore')

# 파일 불러오기
def read_data(file):
    try:
        output = pd.read_excel(file)
    except:
        def read_xlsx(name):
            instance = xw.App(visible=False)
            xlsx_data = xw.Book(name).sheets[0]
            df = xlsx_data.range('A1').options(pd.DataFrame, index = False, expand = 'table').value
            instance.quit()
            instance.kill()
            return df
        output = read_xlsx(file)
    return output

# 셀레늄 실행
def get_driver(viz_opt = False):
    options = Options()
    options.add_argument('--headless')
    
    if viz_opt:
        return webdriver.Chrome()
    else:
        return webdriver.Chrome(options=options)

# RPA 코드 실행
def main():
    opt = 'IB전략'
    ### STEP1. 수집 시작 및 종료 날짜 할당
    # 신고서 제출일, 상장일, 수요예측일 간 차이를 반영하기 위해서 start_dt,start_dt2, start_dt3를 할당
    today = date.today()
    end_dt = datetime.strftime(today, '%Y-%m-%d')
    diff_day = timedelta(days=60)
    start_dt = datetime.strftime(today - diff_day, '%Y-%m-%d')
    start_dt2 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 80), '%Y-%m-%d')
    start_dt3 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 180), '%Y-%m-%d')
    
    ### STEP2. opendartreader 활용, 주어진 기간 내 증권신고서, 증권발행실적 보고서 가져오기
    dart_df, dart = initial_set(start_dt2, end_dt)

    ### STEP3. KIND 수집 항목 가져오기, 셀레늄 사용, 이 경우 viz_opt를 True로 함으로써 수집해야 함, False 시 조회 불가
    driver = get_driver(viz_opt = True)
    driver.set_window_size(1920, 1080)
    table = set_kind(driver, start_dt3, end_dt)
    kind_output = get_kind_inner(driver, table)
    first_df = post_proc(dart_df, kind_output, start_dt)

    ### STEP4. ipo stock 수집 항목 가져오기, 셀레늄 사용
    driver = get_driver()
    driver.set_window_size(1920, 1080)
    ipo_df = ipo_main(driver, first_df)
    first_df = pd.merge(first_df, ipo_df, on = 'corp_name', how = 'left')
    first_df.replace(np.NaN, 0, inplace = True)
    first_df['key'] = [change_join(x) if "스팩" in x else x for x in list(first_df.corp_name)]

    ### STEP5. 38커뮤니케이션 수집 항목 가져오기
    outer_df = get_38(start_dt, end_dt)
    second_df = pd.merge(first_df, outer_df, left_on = 'key', right_on = '기업명', how = 'inner')
    del second_df['기업명'], second_df['key'], second_df['stock_code_x']
    second_df.rename(columns = {'stock_code_y':'stock_code'}, inplace = True)

    ### STEP6. 현업 양식에 맞게끔 변경, opendartreader 활용, 인수인 정보 수집
    third_df = get_dd(dart, second_df)
    third_df, fourth_df = get_d_tables(dart, third_df)
    head_df = change_form(third_df, opt)

    ### STEP7. 파일 저장 및 갱신
    data_path = './datasets/'

    if not os.path.isdir(data_path):
        os.mkdir(data_path)

    if os.path.isfile(data_path + "ib-strategy-data.xlsx"):
        origin_df = read_data(data_path + "ib-strategy-data.xlsx")
        origin_df = pd.concat([origin_df, head_df]).sort_values("수요예측(시작일)").drop_duplicates()
        origin_df.to_excel(data_path + "ib-strategy-data.xlsx", index = False)
    else:
        head_df.to_excel(data_path + "ib-strategy-data.xlsx", index = False)

In [2]:
opt = 'IB전략'
### STEP1. 수집 시작 및 종료 날짜 할당
# 신고서 제출일, 상장일, 수요예측일 간 차이를 반영하기 위해서 start_dt,start_dt2, start_dt3를 할당
today = date.today()
end_dt = datetime.strftime(today, '%Y-%m-%d')
diff_day = timedelta(days=60)
start_dt = datetime.strftime(today - diff_day, '%Y-%m-%d')
start_dt2 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 80), '%Y-%m-%d')
start_dt3 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 180), '%Y-%m-%d')

In [9]:
start_dt = '2023-06-22'
end_dt = '2023-07-21'
start_dt2 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 80), '%Y-%m-%d')
start_dt3 = datetime.strftime(datetime.strptime(end_dt, '%Y-%m-%d') - timedelta(days = 180), '%Y-%m-%d')

In [10]:
### STEP2. opendartreader 활용, 주어진 기간 내 증권신고서, 증권발행실적 보고서 가져오기
dart_df, dart = initial_set(start_dt2, end_dt)

In [11]:
# 상장 기업들
dart_df1 = dart_df.loc[dart_df.stock_code != '']
# 상장전 기업들
dart_df2 = dart_df.loc[dart_df.stock_code == '']

### STEP3. KIND 수집 항목 가져오기, 셀레늄 사용, 이 경우 viz_opt를 True로 함으로써 수집해야 함, False 시 조회 불가
driver = get_driver(viz_opt = True)
driver.set_window_size(1920, 1080)
first_df = kind_main(driver, dart_df1, start_dt3, end_dt)

driver = get_driver(viz_opt = True)
driver.set_window_size(1920, 1080)
table = set_kind(driver, start_dt3, end_dt)
kind_output = get_kind_inner(driver, table)
first_df2 = post_proc(dart_df2, kind_output, start_dt)
first_df = pd.concat([first_df, first_df2]).drop_duplicates()

In [ ]:
'''
# 상장 기업들
dart_df1 = dart_df.loc[dart_df.stock_code != '']
# 상장전 기업들
dart_df2 = dart_df.loc[dart_df.stock_code == '']

### STEP3. KIND 수집 항목 가져오기, 셀레늄 사용, 이 경우 viz_opt를 True로 함으로써 수집해야 함, False 시 조회 불가
driver = get_driver()
driver.set_window_size(1920, 1080)
first_df = kind_main(driver, dart_df1, start_dt3, end_dt)

driver = get_driver(viz_opt = True)
driver.set_window_size(1920, 1080)
table = set_kind(driver, start_dt3, end_dt)
kind_output = get_kind_inner(driver, table)
first_df2 = post_proc(dart_df2, kind_output, start_dt)
first_df = pd.concat([first_df, first_df2]).drop_duplicates()
'''

In [7]:
### STEP4. ipo stock 수집 항목 가져오기, 셀레늄 사용
driver = get_driver()
driver.set_window_size(1920, 1080)
ipo_df = ipo_main(driver, first_df)
first_df = pd.merge(first_df, ipo_df, on = 'corp_name', how = 'left')
first_df.replace(np.NaN, 0, inplace = True)
first_df['key'] = [change_join(x) if "스팩" in x else x for x in list(first_df.corp_name)]

In [65]:
driver = get_driver(viz_opt=True)
driver.set_window_size(1920, 1080)

In [66]:
info_df = first_df

In [67]:
# driver 실행
url = 'http://www.ipostock.co.kr/sub03/ipo05.asp'

col_names = [x+"매출액" + "({})".format(y) for x, y in zip(['당해연도', '직전연도', '전전연도'], ['T', 'T-1', 'T-2'])]
col_names.extend([x+"영업이익" + "({})".format(y) for x, y in zip(['당해연도', '직전연도', '전전연도'], ['T', 'T-1', 'T-2'])])
col_names.extend([x+"당기순이익" + "({})".format(y) for x, y in zip(['당해연도', '직전연도', '전전연도'], ['T', 'T-1', 'T-2'])])

cnt = 0

In [68]:
for idx, corp_name in enumerate(info_df.corp_name):
    driver.get(url)
    wait = WebDriverWait(driver, 10, poll_frequency=0.25)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 
                                               'body > table:nth-child(1) > tbody > tr:nth-child(3) > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td > form > table > tbody > tr:nth-child(2) > td > input.GBOX')))

    search_element = driver.find_element(By.CSS_SELECTOR,
                                         'body > table:nth-child(1) > tbody > tr:nth-child(3) > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td > form > table > tbody > tr:nth-child(2) > td > input.GBOX')
    search_element.click()
    time.sleep(0.1)
    search_element.send_keys(corp_name)
    driver.find_element(By.CSS_SELECTOR, 
                   'body > table:nth-child(1) > tbody > tr:nth-child(3) > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td > form > table > tbody > tr:nth-child(2) > td > input[type=image]:nth-child(2)').click()

    td_values = driver.find_elements(By.CSS_SELECTOR, 
                                     '#print > table > tbody > tr:nth-child(4) > td > table > tbody > tr:nth-child(1) > td:nth-child(2) > a')

    if len(td_values) > 0:
        td_values[0].click()
    else:
        continue

    # 주주구성
    try:
        driver.find_element(By.CSS_SELECTOR, 'img[alt="주주구성"]').click()
        wait = WebDriverWait(driver, 5, poll_frequency=0.25)
        wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="print"]/table/tbody/tr[8]/td/table[2]/tbody')))

        raw_tbls = pd.read_html(driver.page_source, header = 0)
        tbls1 = [x for x in raw_tbls if "보유주식" in x][0]
        u_cnt = tbls1.loc[tbls1['구 분'] == '공모후 상장주식수', ['보유주식']].values[0][0]
    except:
        u_cnt = 0

    try:
        # 재무정보
        driver.find_element(By.CSS_SELECTOR, 'img[alt="재무정보"]').click()

        wait = WebDriverWait(driver, 5, poll_frequency=0.25)
        wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="print"]/table/tbody/tr[6]/td/table[2]')))

        raw_tbls = pd.read_html(driver.page_source, header = 0)
        tbls = [x for x in raw_tbls if "구분" in x][0]

        df = np.array(tbls.loc[tbls['구분'].isin(['매출액', '영업이익', '당기순이익'])].iloc[:, 1:]).reshape(1, -1)[0]

        t_year = tbls.loc[tbls['구분'] == '구분'].iloc[:, 1].values[0].split("년")[0]

        df_change = pd.DataFrame.from_dict({x:[y] for x,y in zip(col_names, df)})
        df_change['기준연도(T=)'] = t_year
        df_change.index = [0]
        df_change['유통가능주식수'] = u_cnt

    except:
        df_change = pd.DataFrame.from_dict({x:[0] for x in col_names})
        df_change.index = [0]
        df_change['기준연도(T=)'] = '-'
        df_change['유통가능주식수'] = u_cnt

    df_change['corp_name'] = corp_name

    if cnt == 0:
        ipo_df = df_change
        cnt += 1
    else:
        ipo_df = pd.concat([ipo_df, df_change])

driver.close()

ipo_df['유통가능주식수'] = [cleansing(x) for x in ipo_df['유통가능주식수']]
ipo_df.loc[:, col_names] = ipo_df.loc[:, col_names].astype(float)

In [16]:
ipo_df.head(2)

,당해연도매출액(T),직전연도매출액(T-1),전전연도매출액(T-2),당해연도영업이익(T),직전연도영업이익(T-1),전전연도영업이익(T-2),당해연도당기순이익(T),직전연도당기순이익(T-1),전전연도당기순이익(T-2),기준연도(T=),유통가능주식수,corp_name
0,4.431885e+10,4.184181e+10,3.069918e+10,8.025840e+09,5.591579e+09,7.122844e+09,1.426009e+10,5.681904e+09,9.772864e+09,2022.12.31 현재,8489671,에이엘티
0,-1.414226e+10,-4.660286e+09,-1.450079e+09,-8.481198e+09,-8.976355e+09,-1.532953e+09,NaN,NaN,NaN,(제7기),10540000,버넥트

In [17]:
ipo_df.columns

Index(['당해연도매출액(T)', '직전연도매출액(T-1)', '전전연도매출액(T-2)', '당해연도영업이익(T)',
       '직전연도영업이익(T-1)', '전전연도영업이익(T-2)', '당해연도당기순이익(T)', '직전연도당기순이익(T-1)',
       '전전연도당기순이익(T-2)', '기준연도(T=)', '유통가능주식수', 'corp_name'],
      dtype='object')

In [23]:
### STEP5. 38커뮤니케이션 수집 항목 가져오기
outer_df = get_38(start_dt, '2023-08-23')

In [25]:
outer_df

              기업명 stock_code  하단공모가액  상단공모가액 의무보유 확약      기관 경쟁률
0          시지트로닉스     429270   18000   20000   5.62%  1,703.85:1
1        유안타스팩14호     450940    2000    2000   1.20%  1,248.32:1
2            에이엘티     172670   16700   20500  16.07%  1,835.71:1
3        파로스아이바이오     388870   14000   18000   1.32%    303.31:1
4             버넥트     438700   11500   13600   8.63%  1,520.08:1
5            뷰티스킨     406820   21000   24000  10.93%   1819.7 :1
6        SK증권스팩9호     455910    2000    2000   3.54%  1,002.51:1
7             센서뷰     321370    2900    3600   7.41%  1,673.33:1
8             와이랩     432430    7000    8000  14.72%   1821.64:1
9            필에너지     378340   26300   30000  59.23%   1811.55:1
10      디비금융스팩11호     456440    2000    2000   7.35%      614.07
11        이노시뮬레이션     274400   13000   15000   5.98%  1,869.47:1
12        교보스팩14호     456490    2000    2000       -    530.34:1
13            오픈놀     440320   11000   13500   0.58%    510.36:1
14            시큐센     232830    2000    2400  12.47%   1800.86:1
15             알멕     354320   40000   45000  51.12%  1,697.23:1
16        하나스팩29호     454640    2000    2000       -    512.17:1
17        KB스팩25호     455250    2000    2000   8.05%    459.10:1
18         하이스팩8호     450050    2000    2000       -    413.20:1
19        NH스팩29호     451700    2000    2000       -     70.13:1
20          프로테옴텍     303360    5400    6600  21.25%     94.10:1
21           큐라티스     348080    6500    8000       -     52.89:1
22           마녀공장     439090   12000   14000  38.57%  1,800.47:1
23           나라셀라     405920   20000   24000   1.19%    178.47:1
24    진영(구.진영엘디엠)     285800    3600    4200   9.17%  1,595.70:1
25           기가비스     420770   34400   39700  49.52%  1,669.60:1
26           모니터랩     434480    7500    9800   6.06%  1,715.41:1
27           씨유박스     340810   17200   23200   3.69%     86.44:1
28         키움스팩8호     446840    2000    2000       -     21.25:1
29            트루엔     417790   10000   12000   8.24%  1,688.87:1
30       에스바이오메딕스     304360   16000   18000   1.94%    854.29:1
31         토마토시스템     393210   18200   22200   3.85%    363.22:1
32        마이크로투나노     424980   13500   15500  10.83%  1,716.98:1
33      IBKS스팩22호     448760    2000    2000       -    334.37:1
34     미래에셋비전스팩3호     448830    2000    2000   1.77%    168.97:1
35     삼성FN리츠(유가)     448730    5000    5000   8.03%       24.88
36        하나스팩27호     448370    2000    2000       -     37.12:1
37       지아이이노베이션     358570   16000   21000   0.23%     26.70:1
38       엘비인베스트먼트     309960    4400    5100   2.84%  1,298.41:1
39  한화위탁관리부동산투자회사     451800    5000    5000  55.78%       7.2:1

In [18]:
### STEP5. 38커뮤니케이션 수집 항목 가져오기
outer_df = get_38(start_dt, end_dt)
second_df = pd.merge(first_df, outer_df, left_on = 'key', right_on = '기업명', how = 'inner')
del second_df['기업명'], second_df['key'], second_df['stock_code_x']
second_df.rename(columns = {'stock_code_y':'stock_code'}, inplace = True)

In [ ]:
outer_df

In [19]:
outer_df.head(2)

        기업명 stock_code  하단공모가액  상단공모가액 의무보유 확약      기관 경쟁률
0  유안타스팩14호     450940    2000    2000   1.20%  1,248.32:1
1      에이엘티     172670   16700   20500  16.07%  1,835.71:1

In [20]:
outer_df.columns

Index(['기업명', 'stock_code', '하단공모가액', '상단공모가액', '의무보유 확약', '기관 경쟁률'], dtype='object')

In [21]:
### STEP6. 현업 양식에 맞게끔 변경, opendartreader 활용, 인수인 정보 수집
third_df = get_dd(dart, second_df)
third_df, fourth_df = get_d_tables(dart, third_df)
head_df = change_form(third_df, opt)

In [22]:
third_df.head(2)

,corp_code,corp_name,corp_cls,rcept_no,상장주식수,주요제품,상장주선인,공모가,경쟁률,신주모집,...,전전연도당기순이익(T-2),기준연도(T=),유통가능주식수,stock_code,하단공모가액,상단공모가액,의무보유 확약,기관 경쟁률,대표주관회사,인수회사
0,00493325,에이엘티,기타,20230720000276,8489671,"Wafer Test, Final Test, COG, Ring Cut",미래에셋증권 주식회사,25000,0,900000,...,9.772864e+09,2022.12.31 현재,8489671.0,172670,16700,20500,16.07%,"1,835.71:1",미래,미래
1,01605529,버넥트,기타,20230720000213,10540000,산업용 XR 솔루션,대신증권㈜,16000,0,1600000,...,0.000000e+00,(제7기),10540000.0,438700,11500,13600,8.63%,"1,520.08:1",대신,대신

In [23]:
third_df.columns

Index(['corp_code', 'corp_name', 'corp_cls', 'rcept_no', '상장주식수', '주요제품',
       '상장주선인', '공모가', '경쟁률', '신주모집', '구주매출', '기관배정수량', '상장일', '납입일', '공모주식수',
       '수요예측(시작일)', '수요예측(종료일)', '청약일', '당해연도매출액(T)', '직전연도매출액(T-1)',
       '전전연도매출액(T-2)', '당해연도영업이익(T)', '직전연도영업이익(T-1)', '전전연도영업이익(T-2)',
       '당해연도당기순이익(T)', '직전연도당기순이익(T-1)', '전전연도당기순이익(T-2)', '기준연도(T=)',
       '유통가능주식수', 'stock_code', '하단공모가액', '상단공모가액', '의무보유 확약', '기관 경쟁률',
       '대표주관회사', '인수회사'],
      dtype='object')

In [24]:
fourth_df.head(2)

,corp_code,corp_name,corp_cls,rcept_no,상장주식수,주요제품,상장주선인,공모가,경쟁률,신주모집,...,상단공모가액,의무보유 확약,기관 경쟁률,대표주관회사,인수회사,인수기관,인수수량,인수금액,비율,비고
0,00493325,에이엘티,기타,20230720000276,8489671,"Wafer Test, Final Test, COG, Ring Cut",미래에셋증권 주식회사,25000,0,900000,...,20500,16.07%,"1,835.71:1",미래,미래,미래,900000,22500000000,100.0,대표주관회사
1,01605529,버넥트,기타,20230720000213,10540000,산업용 XR 솔루션,대신증권㈜,16000,0,1600000,...,13600,8.63%,"1,520.08:1",대신,대신,대신,1920000,30720000000,100.0,대표주관회사

In [25]:
fourth_df.columns

Index(['corp_code', 'corp_name', 'corp_cls', 'rcept_no', '상장주식수', '주요제품',
       '상장주선인', '공모가', '경쟁률', '신주모집', '구주매출', '기관배정수량', '상장일', '납입일', '공모주식수',
       '수요예측(시작일)', '수요예측(종료일)', '청약일', '당해연도매출액(T)', '직전연도매출액(T-1)',
       '전전연도매출액(T-2)', '당해연도영업이익(T)', '직전연도영업이익(T-1)', '전전연도영업이익(T-2)',
       '당해연도당기순이익(T)', '직전연도당기순이익(T-1)', '전전연도당기순이익(T-2)', '기준연도(T=)',
       '유통가능주식수', 'stock_code', '하단공모가액', '상단공모가액', '의무보유 확약', '기관 경쟁률',
       '대표주관회사', '인수회사', '인수기관', '인수수량', '인수금액', '비율', '비고'],
      dtype='object')

In [ ]:
### STEP7. 파일 저장 및 갱신
data_path = './datasets/'

if not os.path.isdir(data_path):
    os.mkdir(data_path)

if os.path.isfile(data_path + "ib-strategy-data.xlsx"):
    origin_df = read_data(data_path + "ib-strategy-data.xlsx")
    origin_df = pd.concat([origin_df, head_df]).sort_values("수요예측(시작일)").drop_duplicates()
    origin_df.to_excel(data_path + "ib-strategy-data.xlsx", index = False)
else:
    head_df.to_excel(data_path + "ib-strategy-data.xlsx", index = False)